/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContratoEvento } from '../models/contrato-evento';
export interface ContratoEventoListRespuestaGeneral {
  error?: boolean;
  mensaje?: string | null;
  resultado?: Array<ContratoEvento> | null;
  statusCode?: number;
}
