/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ContratoEvento {
  capacidad?: number | null;
  descripcion?: string | null;
  fecha?: string | null;
  id?: number;
  imagen?: string | null;
  nombre?: string | null;
  ubicacion?: string | null;
}
