/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { ContratoEvento } from './models/contrato-evento';
export { ContratoEventoListRespuestaGeneral } from './models/contrato-evento-list-respuesta-general';
