/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ContratoEventoListRespuestaGeneral } from '../../models/contrato-evento-list-respuesta-general';

export interface ApiEventosObtenerEventosGet$Json$Params {
}

export function apiEventosObtenerEventosGet$Json(http: HttpClient, rootUrl: string, params?: ApiEventosObtenerEventosGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ContratoEventoListRespuestaGeneral>> {
  const rb = new RequestBuilder(rootUrl, apiEventosObtenerEventosGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ContratoEventoListRespuestaGeneral>;
    })
  );
}

apiEventosObtenerEventosGet$Json.PATH = '/api/Eventos/ObtenerEventos';
